services:
    consignment:
        restart: always
        build: ../shippy-service-consignment
        depends_on:
            - datastore
            - vessel
        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDERSS: ":50051" # Used by go-micro
            DB_HOST: "mongodb://datastore:27017"

    vessel:
        restart: always
        build: ../shippy-service-vessel
        depends_on:
            - datastore
        ports:
            - 50052:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051" # Used by go-micro
            DB_HOST: "mongodb://datastore:27017"

    user:
        build: ./shippy-service-user
        depends_on:
            - database
        ports:
            - 50053:50051
        environment:
            MICRO_ADDRESS: ":50051" # Used by go-micro

    cli:
        build: ../shippy-cli-consignment
        depends_on:
            - datastore
            - vessel
            - consignment

    user-cli:
        build: ./shippy-cli-user
    depends_on:
        - user

    datastore:
        image: mongo
        container_name: "datastore"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null

    database:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "admin"
        ports:
            - 5432:5432
